# Generated by Django 4.2.28 on 2026-03-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
