# Generated by Django 4.2.28 on 2026-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dispatch_location",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="warehouse_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="address",
            name="label",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="address",
            name="normalized_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="address",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
